### ISSUE TITLE
Debian 12: Document build & install process

### ISSUE THREAD

**Issue by proegssilb** [ryryog25/ProffieConfig#10] opened 2024-04-18 16:08 UTC
Process for building wx (Debian's won't work, it doesn't enable STL):

```
git clone https://github.com/wxWidgets/wxWidgets.git
cd wxWidgets/
git submodule init
git submodule update --init
mkdir gtk-build; cd gtk-build
../configure --enable-stl --disable-shared
make -j 14
sudo make install
sudo ldconfig
```

(NOTE: I haven't tested with `--disable-shared`, but it is recommended as per [ryrog25](https://github.com/ryryog25/ProffieConfig/issues/10#issuecomment-2064536605) , so it is included here)

And for ProffieConfig:

```
git clone --recursive https://github.com/ryryog25/ProffieConfig
cd ProffieConfig/src
mkdir build && cd build
qmake6 -o Makefile ../src/ProffieConfig.pro
make
cp -r ../resources/linux/arduino-cli resources/
cp -r ../resources/ProffieOS resources/
cp -r ../resources/props resources/
cp -r ../resources/StyleEditor resources/
```

**Comment by proegssilb** [comment] 2024-04-18 16:49
Good note! This worked on my machine, but if there's a typo-level change to make the script more reliable, then I can definitely make some edits without having to test.

**Comment by ryryog25** [comment] 2024-04-18 16:51
Also, if the program is intended to be distributed it's almost certainly a good idea to do `../configure --enable-stl --disable-shared` as otherwise the program will depend on libraries that don't exist unless the end user builds and installs everything custom themselves. (As we're doing a custom build here, the packages provided for linux won't work, and on Windows and macOS package management is a rabbit hole I haven't wanted to delve into.

**Comment by ryryog25** [comment] 2024-04-18 16:51
> Good note! This worked on my machine, but if there's a typo-level change to make the script more reliable, then I can definitely make some edits without having to test.

I've played around with `cp` a bit and I can't seem to find something that works reliably, it might just be a lack of understanding from my part, but it does seem to just be unintended behavior from `cp` itself.

**Comment by ryryog25** [comment] 2024-05-14 06:02
Added [build documentation](https://github.com/ryryog25/ProffieConfig/blob/master/docs/linux-build.md), closing.

**Closed by ryryog25** 2024-05-14 06:02 UTC
Labels: documentation
