### ISSUE TITLE
Working super cool. How about.....

### ISSUE THREAD

**Issue by NoSloppy** [ryryog25/ProffieConfig#2] opened 2023-10-31 07:07 UTC
Looks great and works well, once you know how it works.
First use experience:
I exported the config to my  ProffieOS/config folder but hadn't saved it first.
So Verify Config failed, saying 
```
There was an error while compiling:
error: config/ProffieConfig_autogen.h: No such file or directory
```
The "Verify Config" window was stuck and couldn't be closed, requiring a Force Quit of the app.
My first thoughts were "Where is it read from? Even if I have it in the right place, what if the Config file is renamed to something other than ProffieConfig_autogen.h? Maybe the ReadMe should explain what paths and prerequisite directories need to be used etc..."

So, now after taking a step back and some digging, I now understand what the app is, and that you have a whole ProffieOS installed in the app, and the config is saved to ProffieOS/config inside the Resources directory inside the app package.

I think there should be some instruction that the user's local ProffieOS folder is irrelevant for the operation of this "all-in-one" standalone app so that there isn't confusion like that.

Now that I understand what's going on, let me give you the uninitiated user's perspective. 

This sequence is what happens and seems counterintuitive a bit:
Open app
choose Presets
First inkling is to type in the Preset Name, Font Directory, and Track File fields, but you can't. Ok, I guess I click the (+) button. 
"NewPreset" appears in the black box. Still can't type a Preset Name though. Ok, I guess I need to click on "NewPreset"?
Click on "NewPreset" in the black box, "NewPreset" populates in the Preset Name field. ok cool.
Wait... Still can't type/edit/replace the Preset Name field? Can't type in the other fields either.
Hmm, ok. "Select Blade to Edit Style..." Maybe I have to go to the Blades drop down.
Goto Blades dropdown, looks like i should click the (+). Ok, did that. Options on right are still greyed out. I guess I need to click ON the "Blade 0" that appeared? Ok, yes. Now things are selectable. Cool. set those things and going back to Presets Dropdown.
Now there's "Blade 0" in the 2nd black box. I'm going to click on that now. Ok, a basic StylePtr<Black>() style appears now.
Hey! Now I can edit the fields! Ok cool. Do that, then export somewhere so I can see what it makes.
Open exported file with custom file name, open it, looks good! Cool.

------
Now I know that seems super picky, and I'd be yelling at the user "DUH just click the thing, NOW you can blablabla"
but I wanted to give you the full "I don't use computers much" version of a user walkthrough.

So, maybe a few things to address just to smooth it out?
Documentation with a step by step would be key.
Include that you need to click on the preset and the blade in the boxes in order for the options to become active?

Maybe you should put Blades above Presets in the dropdown, since it's required to be specified first?

I keep going to the "File" menu to save, export, import and so on. Wouldn't that be more typical than a dedicated "Config" menu bar menu item?

Can you put in a check for whether the blade style ends with a comma, and then omit the insertion of one?
Else, you get this:
`>>(),,` 
and it doesn't compile obviously. Just saying that because I know Fett263 opted to include a comma at the end of his Style Library generated styles , so a lot of people are going to be pasting in a comma there.

Maybe put in a greyed out ".wav" in the track field? Some users don't have file name extensions showing and might just use the base name.
Documentation with a reminder to make sure the full path for the font and track is correct would probably be a good idea.
(and mentioning a common folder appended to the Font Search Path etc...)

I know that's a lot, but it's all constructive criticism.

I see so much good stuff here, it's really well done! Don't let my comments mislead you into thinking that I think it's terrible.
I am jealous of the result!
You should see the insanity I did just to make a web page to convert sound font file names!

**Comment by ryryog25** [comment] 2023-10-31 07:12
Dude, this is awesome, it's exactly the kind of feedback I'm looking for! I've only skimmed through right now, but I'll definitely read through everything thoroughly tomorrow (later today?)

I appreciate you taking a look, and I'm glad to hear that, overall, things went well. :)

**Comment by NoSloppy** [comment] 2023-10-31 07:19
Oh, and this popped up when Verify Config got stuck because not saved yet:
![Screenshot 2023-10-31 at 3 18 24 AM](https://github.com/ryryog25/ProffieConfig/assets/53964195/70b2c734-8e66-4658-b636-b8bb0428ce75)

**Comment by ryryog25** [comment] 2023-10-31 13:57
> There was an error while compiling:
error: config/ProffieConfig_autogen.h: No such file or directory

This is... really strange to me, since part of the verify *is* generating/outputting the config, which leads me to believe that failed for some reason, which is concerning...

> Oh, and this popped up when Verify Config got stuck because not saved yet, although none of the buttons or anything on that window are clickable. Just frozen, and need to force quit the app.

There've been a couple oddities with stuff like that on macOS... just weirdness with the dialogs... when the verify fails it should clear the dialog, present the error, and exit the thread, which means that thread must've crashed or had _something_ happen. I've not had issues like this on Linux or Windows, so I'll have to do some testing on my macOS machine later. 

Just to be sure, this only happened the one time?

> I think there should be some instruction that the user's local ProffieOS folder is irrelevant for the operation of this "all-in-one" standalone app so that there isn't confusion like that.

Gotcha

> Now I know that seems super picky, and I'd be yelling at the user "DUH just click the thing, NOW you can blablabla"
but I wanted to give you the full "I don't use computers much" version of a user walkthrough.

Haha, yeah, I get what you mean :)

>  Documentation with a step by step would be key.

I'll write up some docs, for sure.

> Maybe you should put Blades above Presets in the dropdown, since it's required to be specified first?

Done (will be in next release), this order was left over from the order of implementation when I was originally programming everything, I agree it makes more sense to have blades above.

**Comment by ryryog25** [comment] 2023-10-31 14:02
Also, yeah, I've been working with this for a hot second now, so it all seems "intuitive" to me... it's invaluable to have outside perspective.

**Comment by ryryog25** [comment] 2023-10-31 14:12
How does that order look for File? 
![image](https://github.com/ryryog25/ProffieConfig/assets/60193408/0de633b2-6a5b-4fdc-b173-cdcdd802bf95)

Also moved "Blades"
![image](https://github.com/ryryog25/ProffieConfig/assets/60193408/bf0c5717-bfd6-421c-ac1d-1cd221730242)

**Comment by ryryog25** [comment] 2023-10-31 17:01
Ok, I've made it so that if no preset is selected, one will automatically be added upon typing in the name, dir, or track fields.

**Comment by NoSloppy** [comment] 2023-10-31 20:54
> Just to be sure, this only happened the one time?

it happens anytime you verify before saving the config.



> How does that order look for File?
> ![image](https://user-images.githubusercontent.com/60193408/279403516-0de633b2-6a5b-4fdc-b173-cdcdd802bf95.png)

Cool.
How about "Install Dependencies" just be a one time pop-up on first run instead of living in the menu?

**Comment by ryryog25** [comment] 2023-10-31 23:19
Ok... hmm... I'll have to look into that and see if I can reproduce... I can't seem to do it on linux...

Actually, Install Dependencies doesn't need to be on macOS at all, it doesn't do anything on there (macOS is just cool like that) although it might download the arduino stuff, but that's done anyways if it's not there...? I don't recall, lol.

In the case of Windows and Linux, Windows is notorious for drivers going poof or having issues, so I could see it being needed again there, and on linux, well, it's just one of those things that I don't think it hurts to have it there, since I do see a potential for it being needed.

Now, prompting for it to be run the first time, that I definitely want to implement, since it being hidden could be potentially confusing.

**Comment by ryryog25** [comment] 2023-11-01 04:32
Updated the track input to append .wav to the file name (and some QoL changes to go with that)

**Comment by ryryog25** [comment] 2023-11-01 04:50
Updated Preset Editor to automatically remove trailing "," from styles. (Checks for "()," at the end of a preset. Afaik all styles end with this (), so that should catch it)

**Comment by NoSloppy** [comment] 2023-11-02 00:48
> Updated the track input to append .wav to the file name. 

So it will not append if .wav is included by user? I can't try at the moment.
I was suggesting like a greyed out reminder in the field that disappears once filed is clicked to edit . Ya know what I mean? Something like the way an autofill field that suggests the format of a phone number or something like that.


>  Afaik all styles end with this (),
Yes they do. Cool!

**Comment by ryryog25** [comment] 2023-11-02 03:17
> I exported the config to my ProffieOS/config folder but hadn't saved it first.
>So Verify Config failed, saying
>
> ```There was an error while compiling:
> error: config/ProffieConfig_autogen.h: No such file or directory
>```
> The "Verify Config" window was stuck and couldn't be closed, requiring a Force Quit of the app.

I've replicated this issue with v1.1, though it seems to be resolved in master, I'll need to dig into finding out why. Going to focus on the import issues I'm seeing (also seem to be macOS-specific, which is interesting), and I'll circle back around to this.

**Comment by ryryog25** [comment] 2023-11-02 03:54
> > Updated the track input to append .wav to the file name.
> 
> So it will not append if .wav is included by user? I can't try at the moment. I was suggesting like a greyed out reminder in the field that disappears once filed is clicked to edit . Ya know what I mean? Something like the way an autofill field that suggests the format of a phone number or something like that.
> 
> > Afaik all styles end with this (),
> 
> Yes they do. Cool!
> 
> Nice work!

So, as soon as a user types in *something* into the font directory field, `.wav` will be appended to it (but it won't move the cursor around). This works by adding some logic into the processing code (stripping whitespace) which will also strip out the `.wav` file extension if it's present, then it's re-appended after processing is complete, meaning if it was there prior it will be preserved but if it's tampered with it will be restored, and the location of the cursor is left alone.

I think I get what you mean, though I don't think I have a good way of doing that. I could strip all input of .wav and just have ".wav" on the outside of the box, though I like keeping it all inside the box (don't have to deal with formatting inconsistencies across platforms).

If I can figure out what's going on with this (frankly odd) issue, I'll build a new release so you can try it out and lmk what you think, but don't want to release a version in the current state.

**Comment by ryryog25** [comment] 2023-11-02 05:02
> I've replicated this issue with v1.1, though it seems to be resolved in master, I'll need to dig into finding out why. Going to focus on the import issues I'm seeing (also seem to be macOS-specific, which is interesting), and I'll circle back around to this.

I've gone through and I can't seem to figure out what may have caused this. I know I've implemented a several checks around calls that are potentially problematic, I may have added one there/refactored code a bit and forgotten...

Rebuilding the v1.1 code from source and running doesn't produce the issue... so maybe just a bad build? Something got changed without me noticing and didn't get logged? Beyond me...

**Comment by ryryog25** [comment] 2023-11-02 06:23
I fixed up what was causing issues, will release v1.2 shortly if you'd like to check it out.

**Comment by ryryog25** [comment] 2023-11-02 06:45
Next thing on my list will be to write some documentation for this thing.

**Comment by ryryog25** [comment] 2023-11-04 06:45
Added basic documentation for usage, I think that covers everything you mentioned.

Once again, thank you so much for your help and insight, it also is genuinely meaningful to hear your compliment on it being well-done, since this took (and I presume will take, lol) a hot second of my time. :)

**Closed** 2023-11-04 15:19 UTC
Labels: bug, enhancement

**Comment by NoSloppy** [comment] 2024-04-21 19:53
Hey Ry, I'm commenting here as it's a relevant thread. Just got around to downloading Mac version 1.6.6.
Initial experience (didn't read any documentation yet):
Intro Instructional window is not resizeable. On a wide screen monitor, that's left justified text, but buttons all the way right screen justified (awkward).
After the text explaining that setup can be re-run later, and then  "just click 'Add..' to start using " etc..., the only button is "Skip Instructions" , which pops up an "are you sure" confirmation... felt like I clicked the wrong thing. Was looking for "Add..", but that must be on the next screen, I just expected like an OK or Let's Go button indicating I was getting started. 
Next, I chose "import Existing Config", but it doesn't accept filenames that contain a period such as "BC_Darkshadow_7.x.h"
I also think the field should use the .h extension to clarify exactly what the filename and type is.
Additionally, I couldn't just paste a path in instead of using Browse, that results in persisting "Please choose a configuration file to import".
Once I appeased the boxes, it failed to "Config Import Error".
help? :)

**Comment by ryryog25** [comment] 2024-04-21 20:08
> After the text explaining that setup can be re-run later, and then "just click 'Add..' to start using " etc..., the only button is "Skip Instructions" , which pops up an "are you sure" confirmation... felt like I clicked the wrong thing.

Saw your other issue, chances are because the window for the introduction is wrongly-sized, the window that's supposed to pop up beside it is either hidden or pushed off-screen. The Add button is on that other window. Normally things should look like this when you startup the app and get to the tutorial/introduction:
<img width="1379" alt="Screen Shot 2024-04-21 at 15 00 13" src="https://github.com/ryryog25/ProffieConfig/assets/60193408/f8efa343-25df-4c9e-a353-3e6629210af9">

> Next, I chose "import Existing Config", but it doesn't accept filenames that contain a period such as "BC_Darkshadow_7.x.h"

There's two text entries there, one for the filename and one for the configuration name (as it's imported). As a test I created `default_proffieboard_config.copy.h` and I'm able to select it both with the browse dialog and via manually typing it in. The file browser is set to only take in `.h` files, and the name itself doesn't have the `.h` intentionally, it's just a name.

Additionally, pasting in the full path to that `default_proffieboard_config.copy.h` file also seems to work for me. However, what does happen is the *name* field doesn't like having a `.` in the name, so it will still say "Please enter a valid name," allowing `.` in the configuration names is something I can look into.

> Once I appeased the boxes, it failed to "Config Import Error".

Could you post the config that you tried to import? ProffieConfig's gained a lot of resiliency to various configs and styles, but it wouldn't be surprising at all if there's still some edge-cases it doesn't like (Hopefully V2's approach to config parsing will be significantly more resilient)

**Comment by ryryog25** [comment] 2024-04-21 20:13
Also worth mentioning, that introduction essentially *is* the documentation for ProffieConfig 1.6.x.

Obviously less than helpful if there seems to be visual issues with an ultrawide that hide the intent. (I've responded to your other issue with a couple of questions)
